version: '3.9'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:6.5.2-fpm-alpine
    container_name: wp-wordpress
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    # Stupid code
    # command: > 
    #   bash -c "
    #     mkdir -p /var/www/html/wp-content/plugins/hagen
    #     cp -r /host/assets /var/www/html/wp-content/plugins/hagen/assets 
    #     cp -r /host/inc /var/www/html/wp-content/plugins/hagen/inc
    #     cp -r /host/vendor /var/www/html/wp-content/plugins/hagen/vendor
    #     cp -r /host/hagen.php /var/www/html/wp-content/plugins/hagen/hagen.php
    #   "
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      - ../:/host 
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  database:
    # default port 3306
    image: mysql:8.0
    container_name: wp-database
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'
      
  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.15.12-alpine
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "80:80"    # http
      - "443:443"   # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
      
  # adminer - bring up only as needed - bypasses nginx
#  adminer:
#    # default port 9000
#    image: adminer:4-fastcgi
#    container_name: wp-adminer
#    restart: unless-stopped
#    depends_on:
#      - database
#    ports:
#      - "9000:9000"